#!/usr/bin/env bash
# eldensave installer: creates a venv, installs eldensave into it, and wires
# the `eldensave` command into your PATH so it works from anywhere. Fully
# hands-off - just run it from inside the cloned repo.
set -e

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="$REPO_DIR/.venv"
BIN_DIR="$HOME/.local/bin"

echo "==> eldensave installer"
echo "    repo: $REPO_DIR"
echo ""

# --- venv + install -------------------------------------------------------
if [ ! -d "$VENV_DIR" ]; then
    echo "==> Creating virtual environment..."
    python -m venv "$VENV_DIR"
else
    echo "==> Virtual environment already exists, reusing it."
fi

echo "==> Installing eldensave (editable install)..."
"$VENV_DIR/bin/pip" install --upgrade pip --quiet
"$VENV_DIR/bin/pip" install -e "$REPO_DIR" --quiet

# --- eldensave launcher, wired into PATH -----------------------------------
echo "==> Installing 'eldensave' launcher to $BIN_DIR..."
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/eldensave" << LAUNCHER
#!/usr/bin/env bash
# Auto-generated by eldensave's install.sh - launches eldensave from anywhere.
exec "$VENV_DIR/bin/eldensave" "\$@"
LAUNCHER
chmod +x "$BIN_DIR/eldensave"

path_already_set() {
    case ":$PATH:" in
        *":$BIN_DIR:"*) return 0 ;;
        *) return 1 ;;
    esac
}

add_to_shell_rc() {
    local shell_name
    shell_name="$(basename "${SHELL:-bash}")"

    case "$shell_name" in
        fish)
            local fish_conf="$HOME/.config/fish/config.fish"
            mkdir -p "$(dirname "$fish_conf")"
            if ! grep -qs "fish_add_path $BIN_DIR" "$fish_conf"; then
                echo "fish_add_path $BIN_DIR" >> "$fish_conf"
                echo "    Added to $fish_conf"
            fi
            ;;
        zsh)
            local rc="$HOME/.zshrc"
            if ! grep -qs "$BIN_DIR" "$rc" 2>/dev/null; then
                echo "export PATH=\"$BIN_DIR:\$PATH\"" >> "$rc"
                echo "    Added to $rc"
            fi
            ;;
        *)
            local rc="$HOME/.bashrc"
            if ! grep -qs "$BIN_DIR" "$rc" 2>/dev/null; then
                echo "export PATH=\"$BIN_DIR:\$PATH\"" >> "$rc"
                echo "    Added to $rc"
            fi
            ;;
    esac
}

echo "==> Setting up PATH for 'eldensave'..."
if path_already_set; then
    echo "    $BIN_DIR is already on PATH."
else
    add_to_shell_rc
fi

echo ""
echo "==> Done."
echo ""
if path_already_set; then
    echo "Run:  eldensave"
else
    echo "Open a new terminal (or run 'exec \$SHELL'), then run:  eldensave"
fi
